// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrixloglikC
double matrixloglikC(NumericMatrix data, NumericMatrix means, List covmat, NumericMatrix b, NumericMatrix c);
RcppExport SEXP _grtools_matrixloglikC(SEXP dataSEXP, SEXP meansSEXP, SEXP covmatSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type means(meansSEXP);
    Rcpp::traits::input_parameter< List >::type covmat(covmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixloglikC(data, means, covmat, b, c));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_grtools_matrixloglikC", (DL_FUNC) &_grtools_matrixloglikC, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_grtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
