# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixloglikC <- function(data, means, covmat, b, c) {
    .Call('_grtools_matrixloglikC', PACKAGE = 'grtools', data, means, covmat, b, c)
}

